------ GLOBAL STATE
lock = false
playerColor = nil
deckSource = nil
advanced = false
cardBackInput = ""
enableTokenButtons = false
spawnEverythingFaceDown = false
proxyNonStandardLayouts = false
useOGCardBacks = false
improveAllCards = false